<?php
/**
 * SAML 2.0 remote IdP metadata for simpleSAMLphp.
 *
 */

/*
 * UTLogin SAML IdP
 *
 *  The following code was generated by the SimpleSAMLphp metadata converter [1]
 *  using the UTLogin XML metadata [2] as the input.
 *
 *  [1] https://HOSTNAME/simplesaml/admin/metadata-converter.php
 *  [2] https://login.utexas.edu/login/saml2/jsp/exportmetadata.jsp?entityid=https://login.utexas.edu/login&realm=utaustin
 *
 */
$metadata['https://login.utexas.edu/login'] = array (
  'name' => array(
      'en' => 'UTLogin'
  ),
  'entityid' => 'https://login.utexas.edu/login',
  'contacts' =>
  array (
  ),
  'metadata-set' => 'saml20-idp-remote',
  'SingleSignOnService' =>
  array (
    0 =>
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
      'Location' => 'https://login.utexas.edu/login/SSORedirect/metaAlias/utaustin/idp',
    ),
    1 =>
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
      'Location' => 'https://login.utexas.edu/login/SSOPOST/metaAlias/utaustin/idp',
    ),
  ),
  'SingleLogoutService' =>
  array (
  ),
  'ArtifactResolutionService' =>
  array (
    0 =>
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:SOAP',
      'Location' => 'https://login.utexas.edu/login/ArtifactResolver/metaAlias/utaustin/idp',
      'index' => 0,
      'isDefault' => true,
    ),
  ),
  'keys' =>
  array (
    0 =>
    array (
      'encryption' => false,
      'signing' => true,
      'type' => 'X509Certificate',
      'X509Certificate' => '
MIIEHTCCAwWgAwIBAgIEfLdLUDANBgkqhkiG9w0BAQsFADCBvjELMAkGA1UEBhMCVVMxCzAJBgNV
BAgTAlRYMSswKQYDVQQHEyJBdXN0aW4vc3RyZWV0PTEgVW5pdmVyc2l0eSBTdGF0aW9uMSowKAYD
VQQKEyFUaGUgVW5pdmVyc2l0eSBvZiBUZXhhcyBhdCBBdXN0aW4xLjAsBgNVBAsTJUlUUyAtIElu
Zm9ybWF0aW9uIFRlY2hub2xvZ3kgU2VydmljZXMxGTAXBgNVBAMTEGxvZ2luLnV0ZXhhcy5lZHUw
HhcNMTQxMTIxMTc1ODQyWhcNMzQxMTE2MTc1ODQyWjCBvjELMAkGA1UEBhMCVVMxCzAJBgNVBAgT
AlRYMSswKQYDVQQHEyJBdXN0aW4vc3RyZWV0PTEgVW5pdmVyc2l0eSBTdGF0aW9uMSowKAYDVQQK
EyFUaGUgVW5pdmVyc2l0eSBvZiBUZXhhcyBhdCBBdXN0aW4xLjAsBgNVBAsTJUlUUyAtIEluZm9y
bWF0aW9uIFRlY2hub2xvZ3kgU2VydmljZXMxGTAXBgNVBAMTEGxvZ2luLnV0ZXhhcy5lZHUwggEi
MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCdAvNJjQ24m0AHSvGGTdatlpnR8SkD0dgc+K3F
nqDJqfz9onnKWiqjblBwc5wFowpD0nvfmWGU3OXM3eU0rYKKiA4vR4+hGcwCYx0CcG1zHnm/leXh
wx1mZVot/b5ivlrr38CriFXVbJItM2Q5dFr7AKBycpF5xlkDsYyp4K5UHc4v/CP5RPguA5Ngt8/m
kBRJF5uULgmp5Yzjkn4rbxZDZVulsVBmh4j1NZ0r73BeRtU/FUVWRap9AE/FTIU2lRGYPxs7Waa+
g4HIM7yOqrPTh97SxEKKwJ/21EzmbO/uxwqHbEcFLbDrzrxNacigXi6eSqIpVqfs7AEf0hfrmc/V
AgMBAAGjITAfMB0GA1UdDgQWBBSZU9Ln0+X9cNzT/5EUuZvLaWYDGDANBgkqhkiG9w0BAQsFAAOC
AQEASN4veUXSRYqxialDZ74zahTzQBvfv8IDI0f55IPSRUGOqcXQqm6hN1+r1bhdhzD/iGdozULo
7l1fFZT3tLaPlVvXqf1gkHl0IWaqAd53d37fHAmKRpk+7TQ7vS8iB8J+VtGglQ4AjdEypYh/K+rG
NzpHR9y6o1yfzgGQrAa7v/4xVxAMULMFhdrYejHy/ijbJHF5PvtDKCstxugrOkga4GoBDdXURk4g
t77FM8Rv8iRsS5Y19CQf+iHeHsLpuSwGMkyo9n3/s3Fm/O5b+Z6TawaXFespxmXGepWDdmcm8Boq
lJa/Qh7QDdOj7/z383q6aklzeDoIiqCE1GwGh+PIdw==
                    ',
    ),
    1 =>
    array (
      'encryption' => true,
      'signing' => false,
      'type' => 'X509Certificate',
      'X509Certificate' => '
MIIEHTCCAwWgAwIBAgIEfLdLUDANBgkqhkiG9w0BAQsFADCBvjELMAkGA1UEBhMCVVMxCzAJBgNV
BAgTAlRYMSswKQYDVQQHEyJBdXN0aW4vc3RyZWV0PTEgVW5pdmVyc2l0eSBTdGF0aW9uMSowKAYD
VQQKEyFUaGUgVW5pdmVyc2l0eSBvZiBUZXhhcyBhdCBBdXN0aW4xLjAsBgNVBAsTJUlUUyAtIElu
Zm9ybWF0aW9uIFRlY2hub2xvZ3kgU2VydmljZXMxGTAXBgNVBAMTEGxvZ2luLnV0ZXhhcy5lZHUw
HhcNMTQxMTIxMTc1ODQyWhcNMzQxMTE2MTc1ODQyWjCBvjELMAkGA1UEBhMCVVMxCzAJBgNVBAgT
AlRYMSswKQYDVQQHEyJBdXN0aW4vc3RyZWV0PTEgVW5pdmVyc2l0eSBTdGF0aW9uMSowKAYDVQQK
EyFUaGUgVW5pdmVyc2l0eSBvZiBUZXhhcyBhdCBBdXN0aW4xLjAsBgNVBAsTJUlUUyAtIEluZm9y
bWF0aW9uIFRlY2hub2xvZ3kgU2VydmljZXMxGTAXBgNVBAMTEGxvZ2luLnV0ZXhhcy5lZHUwggEi
MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCdAvNJjQ24m0AHSvGGTdatlpnR8SkD0dgc+K3F
nqDJqfz9onnKWiqjblBwc5wFowpD0nvfmWGU3OXM3eU0rYKKiA4vR4+hGcwCYx0CcG1zHnm/leXh
wx1mZVot/b5ivlrr38CriFXVbJItM2Q5dFr7AKBycpF5xlkDsYyp4K5UHc4v/CP5RPguA5Ngt8/m
kBRJF5uULgmp5Yzjkn4rbxZDZVulsVBmh4j1NZ0r73BeRtU/FUVWRap9AE/FTIU2lRGYPxs7Waa+
g4HIM7yOqrPTh97SxEKKwJ/21EzmbO/uxwqHbEcFLbDrzrxNacigXi6eSqIpVqfs7AEf0hfrmc/V
AgMBAAGjITAfMB0GA1UdDgQWBBSZU9Ln0+X9cNzT/5EUuZvLaWYDGDANBgkqhkiG9w0BAQsFAAOC
AQEASN4veUXSRYqxialDZ74zahTzQBvfv8IDI0f55IPSRUGOqcXQqm6hN1+r1bhdhzD/iGdozULo
7l1fFZT3tLaPlVvXqf1gkHl0IWaqAd53d37fHAmKRpk+7TQ7vS8iB8J+VtGglQ4AjdEypYh/K+rG
NzpHR9y6o1yfzgGQrAa7v/4xVxAMULMFhdrYejHy/ijbJHF5PvtDKCstxugrOkga4GoBDdXURk4g
t77FM8Rv8iRsS5Y19CQf+iHeHsLpuSwGMkyo9n3/s3Fm/O5b+Z6TawaXFespxmXGepWDdmcm8Boq
lJa/Qh7QDdOj7/z383q6aklzeDoIiqCE1GwGh+PIdw==
                    ',
    ),
      ),
  );
