<?php
/**
 * @file
 * Module file for the Photo Content Area module.
 */

/**
 * Implements hook_field_info().
 *
 * Defines a compound field for photo content area.
 */
function utexas_photo_content_area_field_info() {
  return array(
    'utexas_photo_content_area' => array(
      'label' => t('Photo Content Area'),
      'description' => t('Defines a compound field for photo content area'),
      'settings' => array(),
      'instance_settings' => array(),
      'default_widget' => 'utexas_photo_content_area',
      'default_formatter' => 'utexas_photo_content_area',
    ),
  );
}

/**
 * Implements hook_field_widget_info().
 *
 * Defines the default widget for the Quick Links compound field.
 */
function utexas_photo_content_area_field_widget_info() {
  return array(
    'utexas_photo_content_area' => array(
      'label' => t('Photo Content Area'),
      'field types' => array('utexas_photo_content_area'),
      'settings' => array(
        'max_links' => 1,
      ),
    ),
  );
}

/**
 * Implements hook_field_widget_settings_form().
 *
 * Has one option to determine the maximum number of links available.
 */
function utexas_photo_content_area_field_widget_settings_form($field, $instance) {
  $widget = $instance['widget'];
  $settings = $widget['settings'];
  $form = array();

  switch ($widget['type']) {
    case 'utexas_photo_content_area':
      $form['max_links'] = array(
        '#type' => 'textfield',
        '#title' => t('Max number of links'),
        '#description' => t('Enter a maximum number of links that the field can support. Recommended to be no greater than 8.'),
        '#default_value' => $settings['max_links'],
        '#required' => TRUE,
        '#element_validate' => array('element_validate_integer_positive'),
      );
      break;
  }
  return $form;
}

/**
 * Implements hook_field_widget_form().
 *
 * Form definition for the field widget.
 *
 * @see _utexas_photo_content_area_add_link_empty_row()
 */
function utexas_photo_content_area_field_widget_form(&$form, &$form_state, $field,
  $instance, $langcode, $items, $delta, $element) {
  switch ($instance['widget']['type']) {
    case 'utexas_photo_content_area':

      // Image upload input.
      $element['utexas_photo_content_area_image'] = array(
        '#type' => 'media',
        '#title' => t('Photo Image'),
        '#tree' => TRUE,
        '#field_name' => 'utexas_photo_content_area_image',
        '#description' => t('Add a photo with brief copy and any links you need to accompany it.'),
        '#extended' => TRUE,
        '#media_options' => array(
          'global' => array(
            'file_extensions' => 'gif png jpg jpeg',
            'file_directory' => 'photo-content-area',
            'types' => array('image'),
          ),
        ),
        '#default_value' => array('fid' => isset($items[$delta]['image_fid']) ? $items[$delta]['image_fid'] : 0),
      );

      // Headline.
      $element['credit'] = array(
        '#type' => 'textfield',
        '#title' => t('Photo Credit'),
        '#size' => 60,
        '#maxlength' => 100,
        '#default_value' => (isset($items[$delta]['credit'])) ? $items[$delta]['credit'] : '',
        '#description' => 'Optional attribution displayed below the photo.',
      );

      // Headline.
      $element['headline'] = array(
        '#type' => 'textfield',
        '#title' => t('Headline'),
        '#size' => 60,
        '#maxlength' => 100,
        '#default_value' => (isset($items[$delta]['headline'])) ? $items[$delta]['headline'] : '',
      );

      // Copy.
      $element['copy'] = array(
        '#type' => 'text_format',
        '#title' => t('Copy'),
        '#default_value' => (isset($items[$delta]['copy_value'])) ? $items[$delta]['copy_value'] : '',
        '#format' => (isset($items[$delta]['copy_format'])) ? $items[$delta]['copy_format'] : NULL,
        '#wysiwyg' => FALSE,
      );

      // Links.
      $element['links'] = array(
        '#type' => 'fieldset',
        '#collapsible' => FALSE,
        '#title' => t('Links'),
      );

      // Build the elements for the Links.
      $links = array();
      $link_delta = 0;
      $stored_links = (isset($items[0]['links']) && is_string($items[0]['links'])) ? unserialize($items[$delta]['links']) : FALSE;
      if ($stored_links != FALSE) {
        for ($link_delta = 0; $link_delta < count($stored_links); $link_delta++) {
          if (isset($stored_links[$link_delta])) {
            // Populate existing links.
            $links[] = array(
              'link_title' => array(
                '#type' => 'textfield',
                '#maxlength' => 128,
                '#default_value' => $stored_links[$link_delta]['link_title'],
              ),
              'link_url' => array(
                '#type' => 'textfield',
                '#maxlength' => 255,
                '#default_value' => drupal_get_path_alias($stored_links[$link_delta]['link_url']),
              ),
              '_weight' => array(
                '#type' => 'weight',
                '#default_value' => $stored_links[$link_delta]['_weight'],
                '#delta' => 10,
                '#title_display' => 'invisible',
                '#title' => t('Weight for Link'),
              ),
            );
          }
        }
      }

      // Fill up remaining slots with empty rows till the default limit.
      while ($link_delta < $instance['widget']['settings']['max_links'] - 1) {
        $links[] = _utexas_photo_content_area_add_link_empty_row($link_delta);
        $link_delta++;
      }

      // Ensure there is always one empty row available.
      $links[] = _utexas_photo_content_area_add_link_empty_row($link_delta);

      // Attach the remainder of the form.
      $element['links'] = $links;
      $element['links']['#theme'] = 'utexas_photo_content_area_link_table';
      $element['links'] += array(
        '#type' => 'fieldset',
        '#title' => t('Links'),
        '#description' => t('The link title is limited to 128 characters maximum. If items are full, an additional row will be provided upon save.'),
        '#attributes' => array('class' => array('half-width')),
        '#attached' => array(
          'css' => array(drupal_get_path('module', 'utexas_photo_content_area') .
            '/theme/utexas_photo_content_area.css',
          ),
        ),
      );
  }
  return $element;
}

/**
 * Implements hook_field_validate().
 *
 * Used to validate that Photo Content Area have all required field information.
 */
function utexas_photo_content_area_field_validate($entity_type, $entity, $field,
  $instance, $langcode, $items, &$errors) {

  foreach ($items as $delta => $item) {

    if (!empty($item) and !utexas_photo_content_area_field_is_empty($item, $field)) {

      $haslink = 0;
      if (is_array($item['links'])) {
        // Reset links.
        $item['links'] = _utexas_photo_content_area_order_links($item['links']);

        foreach ($item['links'] as $link) {
          // Make sure links are valid links.
          if (!empty($link['link_url'])) {
            $haslink++;
            $target = drupal_get_normal_path($link['link_url']);
            if (!drupal_valid_path($target)) {
              $errors[$field['field_name']][$langcode][$delta][] = array(
                'error' => 'link_invalid',
                'message' => t('%field: The path provided is not a valid URL alias or external link.',
                  array('%field' => $instance['label'])
                ),
              );
            }
          }
          elseif (!empty($link['link_title'])) {
            $errors[$field['field_name']][$langcode][$delta][] = array(
              'error' => 'title_no_link',
              'message' => t('%field: There is a title but no corresponding link.',
              array('%field' => $instance['label'])),
            );
          }
        }

        // Check if tags are included in the headline.
        if (strcmp($item['headline'], strip_tags($item['headline'])) !== 0) {
          $errors[$field['field_name']][$langcode][$delta][] = array(
            'error' => 'headline_tags',
            'message' => t('%field: The headline may not contain HTML.',
              array('%field' => $instance['label'])),
          );
        }
      }
    }
  }
}

/**
 * Implements hook_field_widget_error().
 *
 * Applies sub-field errors to individual form elements.
 */
function utexas_photo_content_area_field_widget_error($element, $error, $form, &$form_state) {
  // Set sub-field errors.
  switch ($error['error']) {
    case 'link_invalid':
      // Loop through the links, flagging all of the elements with a problem.
      foreach (element_children($element['links']) as $key) {
        $link = $element['links'][$key]['link_url']['#value'];
        $target = drupal_get_normal_path($link);
        if (!empty($link) and !drupal_valid_path($target)) {
          form_error($element['links'][$key]['link_url'], $error['message']);
        }
      }
      break;

    case 'title_no_link':
      // Loop through the links, flagging all of the elements with a problem.
      foreach (element_children($element['links']) as $key) {
        $link = $element['links'][$key];
        if (!empty($link['link_title']['#value']) and empty($link['link_url']['#value'])) {
          form_error($element['links'][$key]['link_url'], $error['message']);
        }
      }
      break;

    case 'headline_tags':
      form_error($element['headline'], $error['message']);
      break;

  }
}

/**
 * Implements hook_field_presave().
 *
 * Adjusts field values to save copy and text format into respective columns.
 */
function utexas_photo_content_area_field_presave($entity_type, $entity, $field, $instance, $langcode, &$items) {

  foreach ($items as $delta => &$item) {

    // Adjust copy format & copy value, accounting for form or database format.
    $item['copy_format'] = isset($item['copy']['format']) ? $item['copy']['format'] : $item['copy_format'];
    $item['copy_value'] = isset($item['copy']['value']) ? $item['copy']['value'] : $item['copy_value'];
    unset($item['copy']);

    // Determine whether the fid is coming from a form or from the database,
    // as in the case of a migration.
    if (isset($item['utexas_photo_content_area_image']['fid'])) {
      $item['image_fid'] = $item['utexas_photo_content_area_image']['fid'];
    }
    if (empty($item['image_fid'])) {
      $item['image_fid'] = '0';
    }

    unset($item['utexas_photo_content_area_image']);

    // Adjust links to strip out empty strings.
    $item['links'] = _utexas_photo_content_area_order_links($item['links']);
    $tmp_links = array();
    $tmp_delta = -10;

    foreach ($item['links'] as $key => &$link) {
      if (!empty($link['link_title']) and !empty($link['link_url'])) {
        // Store Drupal path aliases as internal paths, if they exist.
        $target = drupal_get_normal_path($link['link_url']);
        $tmp_links[] = array(
          'link_title' => $link['link_title'],
          'link_url' => $target,
          '_weight' => $tmp_delta,
        );

        $tmp_delta++;
      }
    }
    $item['links'] = serialize($tmp_links);

  }

}

/**
 * Implements hook_file_download().
 *
 * Checks access to make sure users can actually use the files that have been
 * uploaded. Required since Drupal 7.29.
 */
function utexas_photo_content_area_file_download($uri) {
  if (strpos(file_uri_target($uri), 'photo-content-area') === 0) {
    $info = image_get_info($uri);
    return array('Content-Type' => $info['mime_type']);
  }

  return NULL;
}

/**
 * Implements hook_field_insert().
 *
 * Increment file usage.
 */
function utexas_photo_content_area_field_insert($entity_type, $entity, $field,
  $instance, $langcode, &$items) {
  utexas_admin_field_insert_custom($entity_type, $entity, $field,
  $instance, $langcode, $items, 'utexas_photo_content_area');
}


/**
 * Implements hook_field_update().
 *
 * Adjust copy format+value and handle images.
 */
function utexas_photo_content_area_field_update($entity_type, $entity, $field,
  $instance, $langcode, &$items) {
  utexas_admin_field_update_custom($entity_type, $entity, $field,
  $instance, $langcode, $items, 'utexas_photo_content_area');
}

/**
 * Implements hook_field_delete().
 *
 * Cleans up any remaining files, if they have not been deleted already.
 */
function utexas_photo_content_area_field_delete($entity_type, $entity, $field, $instance, $langcode, &$items) {
  utexas_admin_field_delete_custom($entity_type, $entity, $field, $instance, $langcode, $items, 'utexas_photo_content_area');
}

/**
 * Implements hook_field_formatter_info().
 *
 * Defines the primary field widget.
 */
function utexas_photo_content_area_field_formatter_info() {
  return array(
    'utexas_photo_content_area' => array(
      'label' => t('Photo Content Area'),
      'field types' => array('utexas_photo_content_area'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 *
 * Creates the formatter for Photo Content Area.
 */
function utexas_photo_content_area_field_formatter_view($entity_type, $entity, $field,
  $instance, $langcode, $items, $display) {
  $element = array();
  $settings = $display['settings'];

  switch ($display['type']) {
    case 'utexas_photo_content_area':
      foreach ($items as $delta => $item) {
        $element[] = array(
          '#type' => 'markup',
          '#markup' => theme('utexas_photo_content_area', array('item' => $item)),
          '#attached' => array(
            'css' => array(drupal_get_path('module', 'utexas_photo_content_area') .
              '/theme/utexas_photo_content_area.css',
            ),
          ),
        );
      }
      break;
  }
  return $element;
}

/**
 * Implements hook_theme().
 *
 * @see template_preprocess_utexas_photo_content_area()
 */
function utexas_photo_content_area_theme($existing, $type, $theme, $path) {
  return array(
    'utexas_photo_content_area' => array(
      'variables' => array(
        'item' => NULL,
      ),
      'template' => 'theme/utexas-photo-content-area',
    ),
    'utexas_photo_content_area_link_table' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Theme preprocess function for photo content area to create variables.
 *
 * @see utexas_photo_content_area_theme()
 *
 * @see utexas_photo_content_area_image_default_styles()
 *
 * @ingroup themeable
 */
function template_preprocess_utexas_photo_content_area(&$variables) {

  $photo = FALSE;
  $credit = FALSE;
  if (!empty($variables['item']['image_fid'])) {
    if ($file = file_load($variables['item']['image_fid'])) {
      $info = image_get_info($file->uri);
      $photo_credit = field_get_items('file', $file, 'field_photo_credit');
      $credit = isset($variables['item']['credit']) ? $variables['item']['credit'] : FALSE;
      $alt = isset($file->field_file_image_alt_text['und'][0]['safe_value']) ? $alt = $file->field_file_image_alt_text['und'][0]['safe_value'] : '';
      $title = isset($file->field_file_image_title_text['und'][0]['safe_value']) ? $title = $file->field_file_image_title_text['und'][0]['safe_value'] : '';
      $photo = theme('image_style', array(
        'style_name' => 'utexas_photo_content_area_image',
        'path' => $file->uri,
        'width' => $info['width'],
        'height' => $info['height'],
        'alt' => $alt,
        'title' => $title,
        'attributes' => array('class' => array('utexas-photo-content-area')),
      ));
    }
  }
  else {
    $photo = FALSE;
  }

  // Sanitize headline.
  $output = array();
  $headline = (!empty($variables['item']['headline'])) ?
  check_plain($variables['item']['headline']) : FALSE;

  // Grab the copy.
  $copy_value = $variables['item']['copy_value'];
  $copy_format = $variables['item']['copy_format'];
  $copy = (!empty($copy_value) and !empty($copy_format)) ? check_markup($copy_value, $copy_format) : FALSE;

  // Set the links.
  $links = !empty($variables['item']['links']) ? unserialize($variables['item']['links']) : array();
  $tmp_links = array();
  foreach ($links as $link) {
    $tmp_links[] = l('<span>' . $link['link_title'] . '</span>',
      $link['link_url'],
      array(
        'html' => TRUE,
        'attributes' => array(
          'class' => array(
            'cta-link',
            'sans',
          ),
        ),
      )
    );
  }
  $links = (!count($tmp_links)) ? FALSE : theme('item_list', array(
    'items' => $tmp_links,
    'title' => NULL,
    'type' => 'ul',
    'attributes' => array(),
  ));

  // Unset unneeded variables.
  unset($variables['item']);

  // Set the grid class for template file based on region.
  $variables['page_template'] = FALSE;
  if ($node = menu_get_object() and isset($node->field_template['und'][0]['target_id'])) {
    $id = $node->field_template['und'][0]['target_id'];
    $exists = entity_get_info('template');
    if ($exists) {
      $template = entity_load('template', array($id));
      if (isset($template[$id])) {
        $variables['page_template'] = $template[$id]->name;
      }
    }
  }

  // Generate the fieldblock ID for the given field (see fieldblock.module).
  $variable_name = 'fieldblock-node-' . $node->type . '-default';
  $photo_content_area_id = md5($variable_name . '-' . 'field_utexas_photo_content_area');
  $parent_region = utexas_admin_retrieve_parent_region($node->nid, $photo_content_area_id);
  $sidebar_regions = array('sidebar_second', 'content_top_right');
  $grid_class = in_array($parent_region, $sidebar_regions) ? 'medium-12' : 'medium-6';

  // Reset variables.
  $variables += array(
    'headline' => $headline,
    'links' => $links,
    'copy' => $copy,
    'photo' => $photo,
    'credit' => $credit,
    'grid_class' => $grid_class,
  );
}

/**
 * Implements hook_image_default_styles().
 *
 * Defines image styles for photo content area images.
 */
function utexas_photo_content_area_image_default_styles() {
  return array(
    'utexas_photo_content_area_image' => array(
      'label' => t('Photo Content Area Image'),
      'effects' => array(
        array(
          'name' => 'smartcrop_scale_and_crop',
          'data' => array(
            'width' => 450,
            'height' => 600,
            'upscale' => FALSE,
          ),
          'weight' => 0,
        ),
      ),
    ),
  );
}

/**
 * Helper function to sort ordered links by their weight.
 *
 * @param string $item
 *   Serialized render array for an individual link row.
 *
 * @return array
 *   A sorted array of links.
 */
function _utexas_photo_content_area_order_links($item) {

  // Loop through, unsetting the delete link & setting by weights.
  $weight = array();
  $title = array();
  // Determine whether the data is coming from the form or the database,
  // as in the case of a migration.
  $item = (is_array($item)) ? $item : unserialize($item);
  if (!empty($item)) {
    foreach ($item as $key => &$link) {
      $weight[$key] = (int) $link['_weight'];
      $title[$key] = $link['link_title'];
    }

    // Sort by weight, then title and return.
    if (isset($item)) {
      array_multisort($weight, SORT_ASC, $title, SORT_ASC, $item);
    }

    // Strip out empty fields.
    foreach ($item as $key => &$link) {
      if (empty($link['link_title']) and empty($link['link_url'])) {
        unset($link);
      }
    }
  }
  return $item;
}

/**
 * Custom theme function to theme the link table as a tabledrag element.
 */
function theme_utexas_photo_content_area_link_table($variables) {
  $element = $variables['element'];
  $output = '';

  $table_id = drupal_html_id($element['#id'] . '_values');
  $order_class = $element['#id'] . '-delta-order';

  $header = array(
    array('data' => t('Link Title'), 'colspan' => 2),
    t('Link URL'),
    t('Weight'),
  );
  $rows = array();

  // Sort links according to weight.
  $items = array();
  foreach (element_children($element) as $key) {
    $items[] = &$element[$key];
  }
  usort($items, '_utexas_photo_content_area_sort_links_by_weight');

  // Add the links as table rows.
  foreach ($items as $key => $item) {
    $item['_weight']['#attributes']['class'] = array($order_class);
    $delta_element = drupal_render($item['_weight']);
    $cells = array(
      array('data' => '', 'class' => array('field-multiple-drag')),
      drupal_render($item['link_title']),
      drupal_render($item['link_url']),
      array('data' => $delta_element, 'class' => array('delta-order')),
    );
    $rows[] = array(
      'data' => $cells,
      'class' => array('draggable'),
      'id' => $table_id . '-' . $key,
    );
  }

  // Create the table drag.
  $output  = '<div class="link-table">';
  $output .= theme('table', array(
    'header' => $header,
    'rows' => $rows,
    'attributes' => array(
      'id' => $table_id,
    ),
  ));
  $output .= '</div>';

  // Order the table drag.
  drupal_add_tabledrag($table_id, 'order', 'sibling', $order_class);

  return $output;
}

/**
 * Helper function to order links by weight.
 */
function _utexas_photo_content_area_sort_links_by_weight($a, $b) {
  if (isset($a['_weight']) and isset($b['_weight'])) {
    return ($a['_weight']['#value'] < $b['_weight']['#value']) ? -1 : 1;
  }
  return 0;
}

/**
 * Helper function that returns an array representing an empty row.
 *
 * @param int $link_count
 *   Number of links on the form.
 *
 * @return array
 *   Render array for the links.
 */
function _utexas_photo_content_area_add_link_empty_row($link_count) {
  // Define the next one down.
  $max_delta = 10;

  return array(
    'link_title' => array(
      '#type' => 'textfield',
      '#maxlength' => 128,
    ),
    'link_url' => array(
      '#type' => 'textfield',
      '#maxlength' => 128,
      '#attributes' => array(
        'placeholder' => 'external URL (http://...) or internal path (e.g., about/diversity)',
      ),
    ),
    '_weight' => array(
      '#type' => 'weight',
      '#delta' => $max_delta,
      '#default_value' => ($max_delta - $link_count) * -1,
      '#title_display' => 'invisible',
      '#title' => t('Weight for Link'),
    ),
  );
}

/**
 * Implements hook_field_is_empty().
 *
 * Determines whether or not the field has data in it.
 */
function utexas_photo_content_area_field_is_empty($item, $field) {
  switch ($field['type']) {
    case 'utexas_photo_content_area':
      // We check images in multiple places. Handle both implementations.
      $image_empty = (isset($item['utexas_photo_content_area_image'])) ? empty($item['utexas_photo_content_area_image']['fid']) : isset($item['image_fid']);

      return
        _utexas_photo_content_area_links_are_empty($item['links']) and
        $image_empty and
        empty($item['headline']);
  }
  return FALSE;
}

/**
 * Helper function to determine whether or not an array of links is empty.
 *
 * @param string $links
 *   An serialized array representing link form information.
 *
 * @return bool
 *   A boolean representing whether or not that row of links is empty or not.
 */
function _utexas_photo_content_area_links_are_empty($links) {
  $empty = TRUE;

  // Ensure a sanitation of weights + other items.
  $links = _utexas_photo_content_area_order_links($links);

  // We only care if link title or link URL is set.
  foreach ($links as $link) {
    if (!empty($link['link_title']) or !empty($link['link_url'])) {
      $empty = FALSE;
      break;
    }
  }

  return $empty;
}
