<?php
/**
 * @file
 * UTexas Beacon module.
 *
 * This module collects data from an installation of the UTexas distribution
 * and sends it to stewards daily on cron runs.
 */

/**
 * Email recipient for site data.
 */
define('UTEXAS_BEACON_EMAIL_RECIPIENT', variable_get('utexas_beacon_email_recipient', 'drupal-kit-beacon@utlists.utexas.edu'));

/**
 * Implements hook_mail().
 *
 * Prepare a message based on parameters; called from drupal_mail().
 */
function utexas_beacon_mail($key, &$message, $email_params) {
  switch ($key) {
    case 'information':
      $message['subject'] = $email_params['subject'];
      $message['headers']['Content-Type'] = 'text/plain; charset=UTF-8; format=flowed';
      $message['body'][] = $email_params['body'];
      break;
  }
}

/**
 * Builds array of site info.
 */
function _utexas_beacon_prepare_data() {
  $site_data = array();
  $site_data['site_name'] = variable_get('site_name', 'none');
  $site_data['base_url'] = $GLOBALS['base_url'];
  $site_data['ip_address'] = ip_address();
  $site_data['hostname'] = gethostname();
  $site_data['admin_email'] = variable_get('site_mail', 'none');
  $site_data['drupal_version'] = VERSION;
  $site_data['php_version'] = phpversion();

  $install_profile_info = install_profile_info(drupal_get_profile());
  $site_data['active_installation_profile'] = $install_profile_info['name'];
  $site_data['active_installation_profile_distribution_name'] = $install_profile_info['distribution_name'];
  $site_data['active_installation_profile_version'] = $install_profile_info['version'];

  $site_data['current_theme'] = variable_get('theme_default', 'none');
  if ($site_data['current_theme'] == 'forty_acres') {
    $forty_acres_info = system_get_info('theme', 'forty_acres');
    $site_data['forty_acres_version'] = $forty_acres_info['version'];
  }
  if (module_exists('utexas_page_builder')) {
    $site_data['page_builder_enabled'] = 'yes';
    $page_builder_info = system_get_info('module', 'utexas_page_builder');
    $site_data['page_builder_version'] = $page_builder_info['version'];
  }
  else {
    $site_data['page_builder_enabled'] = 'no';
  }
  if (module_exists('utlogin')) {
    $site_data['utlogin_enabled'] = 'yes';
    $utlogin_info = system_get_info('module', 'utlogin');
    $site_data['utlogin_version'] = $utlogin_info['version'];
  }
  else {
    $site_data['utlogin_enabled'] = 'no';
  }
  return $site_data;
}

/**
 * Implements hook_cron().
 *
 * Prepares info and sends email via drupal_mail() once a day.
 */
function utexas_beacon_cron() {
  $site_data_for_mail = _utexas_beacon_prepare_data();
  // Check time of last cron run.
  $cron_last = variable_get('cron_last');
  // Only send email once a day.
  if (isset($cron_last) && date('ymd', $cron_last) != date('ymd', time())) {
    $email_params = array(
      'subject' => 'Utexas distribution installed at ' . $site_data_for_mail['base_url'] . ' phoning home.',
    );
    foreach ($site_data_for_mail as $key => $value) {
      $email_params['body'] .= $key . ': ';
      $email_params['body'] .= $value . "\r\n";
    }
    // Send the email.
    drupal_mail('utexas_beacon', 'information', UTEXAS_BEACON_EMAIL_RECIPIENT, language_default(), $email_params, $from = NULL, $send = TRUE);
  }
}
