<?php

/**
 * @file
 * UTexas Beacon module.
 *
 * This module collects data from an installation of the UTexas distribution
 * and sends it to stewards daily on cron runs.
 */

/**
 * URI of endpoint for site data.
 */
define('UTEXAS_BEACON_ENDPOINT_URI', variable_get('utexas_beacon_endpoint_uri', 'https://drupal-beacon.its.utexas.edu/beacon-end.php'));

/**
 * Email recipient for site data.
 */
define('UTEXAS_BEACON_EMAIL_RECIPIENT', variable_get('utexas_beacon_email_recipient', 'drupal-kit-beacon@utlists.utexas.edu'));

/**
 * Implements hook_mail().
 *
 * Prepare a message based on parameters; called from drupal_mail().
 */
function utexas_beacon_mail($key, &$message, $email_params) {
  switch ($key) {
    case 'information':
      $message['subject'] = $email_params['subject'];
      $message['headers']['Content-Type'] = 'text/plain; charset=UTF-8; format=flowed';
      $message['body'][] = $email_params['body'];
      break;
  }
}

/**
 * Builds array of site info.
 */
function _utexas_beacon_prepare_data() {
  // Make sure the installation API is available.
  include_once DRUPAL_ROOT . '/includes/install.inc';

  $site_data = array();
  $site_data['site_name'] = variable_get('site_name', '');
  $site_data['base_url'] = $GLOBALS['base_url'];
  $site_data['ip_address'] = ip_address();
  $site_data['hostname'] = gethostname();
  $site_data['admin_email'] = variable_get('site_mail', '');
  $site_data['drupal_version'] = VERSION;
  $site_data['php_version'] = phpversion();
  $site_data['page_builder_enabled'] = 0;
  $site_data['utlogin_enabled'] = 0;

  $install_profile_info = install_profile_info(drupal_get_profile());
  $site_data['active_installation_profile'] = $install_profile_info['name'];
  $site_data['active_installation_profile_distribution_name'] = $install_profile_info['distribution_name'];
  $site_data['active_installation_profile_version'] = $install_profile_info['version'];

  $site_data['current_theme'] = variable_get('theme_default', '');
  if ($site_data['current_theme'] == 'forty_acres') {
    $forty_acres_info = system_get_info('theme', 'forty_acres');
    $site_data['forty_acres_version'] = $forty_acres_info['version'];
  }
  if (module_exists('utexas_page_builder')) {
    $site_data['page_builder_enabled'] = 1;
    $page_builder_info = system_get_info('module', 'utexas_page_builder');
    $site_data['page_builder_version'] = $page_builder_info['version'];
  }
  if (module_exists('utlogin')) {
    $site_data['utlogin_enabled'] = 1;
    $utlogin_info = system_get_info('module', 'utlogin');
    $site_data['utlogin_version'] = $utlogin_info['version'];
  }
  if (module_exists('utexas_google_cse')) {
    $site_data['google_cse_id'] = variable_get('utexas_google_cse_id', '');
  }
  if (module_exists('utexas_google_tag_manager')) {
    $site_data['google_tag_manager_code'] = variable_get('utexas_google_tag_manager_gtm_code', '');
  }
  return $site_data;
}

/**
 * Implements hook_cron().
 *
 * Prepares info and posts data via drupal_http_request() or sends email via
 * drupal_mail() once a day.
 */
function utexas_beacon_cron() {
  // Variable for determining whether to email site data to stewards.
  $send_email = FALSE;
  // Retrieve time of last cron run, or default to timestamp of 1 day in past.
  $cron_last = variable_get('cron_last', time() - 24 * 60 * 60);
  // $cron_day is the midnight-time of the day that the last cron ran.
  $cron_day = strtotime('0:00', $cron_last);
  // $today is the midnight-time of the current day.
  $today = strtotime('0:00', time());
  if ($cron_last && $today > $cron_day) {
    // Prepare the data.
    $site_data_for_post = _utexas_beacon_prepare_data();

    // Conditionally send email with site data.
    if ($send_email == TRUE) {
      $email_params = array(
        'subject' => 'Utexas distribution installed at ' . $site_data_for_mail['base_url'] . ' phoning home.',
      );
      $email_params['body'] = '';
      foreach ($site_data_for_mail as $key => $value) {
        $email_params['body'] .= $key . ': ';
        $email_params['body'] .= $value . "\r\n";
      }
      // Send the email.
      drupal_mail('utexas_beacon', 'information', UTEXAS_BEACON_EMAIL_RECIPIENT, language_default(), $email_params, $from = NULL, $send = TRUE);
    }

    // Defaults to POSTing data to beacon endpoint.
    else {
      $options = array(
        'method' => 'POST',
        'data' => drupal_json_encode($site_data_for_post),
        'headers' => array(),
      );
      $options['headers'] += array(
        'X-UTexas-Beacon-Key' => variable_get('utexas_beacon_key', NULL),
        'Content-Type' => 'application/json',
      );
      $response = drupal_http_request(UTEXAS_BEACON_ENDPOINT_URI, $options);
      // The HTTP request must return an expected response code.
      if (in_array($response->code, array(200))) {
        watchdog('utexas_beacon', 'Beacon data logged to ITS Drupal Team.', NULL, WATCHDOG_INFO);
      }
      else {
        $output = 'Beacon HTTP request returned code ';
        $output .= $response->code;
        if (isset($response->error)) {
          $output .= ': ' . $response->error;
        }
        watchdog('utexas_beacon', $output, NULL, WATCHDOG_ERROR);
      }
    }
  }
}
