<?php

/**
 * @file
 * Module file for setting a 404 callback so that menus are generated.
 */

define('UTEXAS_NAVIGATION404_PAGE', 'utexas_navigation404');

/**
 * Implements hook_menu().
 */
function utexas_navigation404_menu() {
  $items[UTEXAS_NAVIGATION404_PAGE] = array(
    'title'           => 'Page not found',
    'access callback' => TRUE,
    'page callback'   => 'utexas_navigation404_404_page',
    'type'            => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Our custom menu callback that returns Drupal's standard 404 message.
 */
function utexas_navigation404_404_page() {
  drupal_set_title(t('Page not found'));
  return t('The requested page could not be found.');
}

/**
 * Implements hook_form_alter().
 */
function utexas_navigation404_form_system_site_information_settings_alter(&$form, $form_state) {
  // Since we don't care what site_404 is set to, let the user set it.
  if ($form['error_page']['site_404']['#default_value'] == UTEXAS_NAVIGATION404_PAGE) {
    $form['error_page']['site_404']['#default_value'] = '';
  }
  // Insert our submit handler first.
  array_unshift($form['#submit'], 'utexas_navigation404_site_404_submit');
}

/**
 * Submit callback for system_site_information_settings form.
 */
function utexas_navigation404_site_404_submit($form, &$form_state) {
  // Make sure site_404 is not empty.
  if ($form_state['values']['site_404'] == '') {
    $form_state['values']['site_404'] = UTEXAS_NAVIGATION404_PAGE;
  }
}
