<?php

/**
 * @file
 * Business logic for UTexas Social Accounts module.
 */

/**
 * Defines which social media items are available.
 *
 * The key => value represents the display name => icon class.
 */
define('UTEXAS_SOCIAL_ACCOUNTS_MEDIA_ITEMS', serialize(
  array(
    'Facebook' => 'icon-facebook',
    'Twitter' => 'icon-twitter',
    'Instagram' => 'icon-instagram',
    'LinkedIn' => 'icon-linkedin',
    'YouTube' => 'icon-youtube3',
    'GooglePlus' => 'icon-googleplus',
    'Flickr' => 'icon-flickr',
    'Pinterest' => 'icon-pinterest',
    'Tumblr'  => 'icon-tumblr',
    'Vimeo' => 'icon-vimeo2',
  )
));

/**
 * Implements hook_menu().
 *
 * Defines an administration path for the module.
 */
function utexas_social_accounts_menu() {
  // Menu items.
  $items = array();

  // Now we create the admin page item.
  $items['admin/config/utexas/utexas-social-accounts'] = array(
    'title' => 'Social Accounts Settings',
    'description' => 'Manage social media accounts for the site header and footer.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('utexas_social_accounts_admin'),
    'access arguments' => array('manage social accounts settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function utexas_social_accounts_permission() {
  return array(
    'manage social accounts settings' => array(
      'title' => t('Manage the social accounts settings'),
    ),
  );
}

/**
 * Implements hook_admin().
 *
 * We use it to create the admin form.
 */
function utexas_social_accounts_admin() {
  $form = array();

  $form['utexas_social_accounts_description']['#markup'] = t('Items with URLs will render as media icons in the site header and footer. Leave the URL field blank to not display the icon. Use the drag-and-drop crosshairs to order the items.');

  $form['fields'] = array(
    '#type' => 'fieldset',
    '#title' => t('Social Accounts'),
    '#theme' => 'utexas_social_accounts_form_table',
    '#prefix' => '<div id="field-table">',
    '#suffix' => '</div>',
  );
  $accounts = unserialize(variable_get('utexas_social_accounts_media_items', UTEXAS_SOCIAL_ACCOUNTS_MEDIA_ITEMS));
  $count = 0;
  $max_delta = 10;
  foreach (array_keys($accounts) as $name) {
    // Converts to strtolower, spaces converted to underscores.
    $machine_name = _utexas_admin_machine_name($name);
    $form['fields']['utexas_social_accounts_' . $machine_name] = array(
      '#type' => 'textfield',
      '#default_value' => variable_get('utexas_social_accounts_' . $machine_name, ''),
      '#size' => 100,
      '#maxlength' => 100,
      '#required' => FALSE,
    );
    $form['fields']['utexas_social_accounts_' . $machine_name . '_weight'] = array(
      '#type' => 'weight',
      '#delta' => $max_delta,
      '#default_value' => variable_get('utexas_social_accounts_' . $machine_name . '_weight', ($max_delta - $count) * -1),
      '#title_display' => 'invisible',
      '#title' => t('Weight'),
    );
    $count++;
  }

  $form['#submit'][] = "_social_accounts_cache_clear";

  return system_settings_form($form);
}

/**
 * Implements hook_theme().
 *
 * Defines the utexas_social_accounts_theme theme function.
 */
function utexas_social_accounts_theme($existing, $type, $theme, $path) {
  return array(
    'utexas_social_accounts' => array(
      'template' => 'utexas-social-accounts',
    ),
    'utexas_social_accounts_form_table' => array(
      'render element' => 'form',
    ),
  );
}

/**
 * Theme process function to put page edit fields into a draggable table.
 */
function theme_utexas_social_accounts_form_table(&$variables) {
  // Get the useful values.
  $form = $variables['form'];
  $output = '';

  $table_id = drupal_html_id($form['#id'] . '_values');
  $order_class = $form['#id'] . '-delta-order';

  $header = array(
    array('data' => t('Account'), 'colspan' => 2),
    t('URL'),
    t('Weight'),
  );
  $rows = array();
  $accounts = unserialize(variable_get('utexas_social_accounts_media_items', UTEXAS_SOCIAL_ACCOUNTS_MEDIA_ITEMS));

  $sorted_fields = array();
  foreach (array_keys($accounts) as $name) {
    $machine_name = _utexas_admin_machine_name($name);
    $weight = $form['utexas_social_accounts_' . $machine_name . '_weight']['#value'];
    $sorted_fields[$name] = $weight;
  }
  asort($sorted_fields);

  // Add the links as table rows.
  foreach (array_keys($sorted_fields) as $name) {
    $machine_name = _utexas_admin_machine_name($name);
    $form['utexas_social_accounts_' . $machine_name . '_weight']['#attributes']['class'] = array($order_class);
    $delta_element = drupal_render($form['utexas_social_accounts_' . $machine_name . '_weight']);
    $cells = array(
      array('data' => drupal_render($form['utexas_social_accounts_' . $machine_name . '_weight']), 'class' => array('field-multiple-drag')),
      array('data' => $name),
      array('data' => drupal_render($form['utexas_social_accounts_' . $machine_name])),
      array('data' => $delta_element, 'class' => array('delta-order')),
    );
    $rows[] = array(
      'data' => $cells,
      'class' => array('draggable'),
      'id' => $table_id . '-' . $machine_name,
    );
  }

  // Create the table drag.
  $output  = '<div class="field-table">';
  $output .= theme('table', array(
    'header' => $header,
    'rows' => $rows,
    'attributes' => array('id' => $table_id),
  ));
  $output .= '</div>';

  // Order the table drag.
  drupal_add_tabledrag($table_id, 'order', 'sibling', $order_class);

  return $output;
}

/**
 * Additional submit handler that triggers a cache clear for immediate update.
 */
function _social_accounts_cache_clear(&$form, $form_state) {
  cache_clear_all(NULL, 'cache_block');
  cache_clear_all(NULL, 'cache_page');
}

/**
 * Implements hook_block_info().
 *
 * Defines the block that will be available at Structure>Blocks.
 */
function utexas_social_accounts_block_info() {
  $blocks = array();

  $blocks['social_accounts_block'] = array(
    'info' => t('Social accounts block'),
    'status' => TRUE,
  );

  return $blocks;
}

/**
 * Implements hook_form_alter().
 *
 * Defines the validate handler function.
 */
function utexas_social_accounts_form_alter(&$form, &$form_state, $form_id) {
  // dsm($form_id);
  if ($form_id == 'utexas_social_accounts_admin') {
    $form['#validate'][] = 'utexas_social_accounts_form_validate';
  }
}

/**
 * Implements utexas_social_accounts_form_validate().
 *
 * Defines the validation for each input field from the admin form.
 */
function utexas_social_accounts_form_validate($form, &$form_state) {
  $accounts = unserialize(variable_get('utexas_social_accounts_media_items', UTEXAS_SOCIAL_ACCOUNTS_MEDIA_ITEMS));
  foreach (array_keys($accounts) as $name) {
    $machine_name = _utexas_admin_machine_name($name);
    if (filter_var($form_state['values']['utexas_social_accounts_' . $machine_name], FILTER_VALIDATE_URL) === FALSE
      && !empty($form_state['values']['utexas_social_accounts_' . $machine_name])) {
      form_set_error('utexas_social_accounts_' . $machine_name, t('There is not a valid URL for the @name account.', array('@name' => $name)));
    }
  }
}

/**
 * Implements hook_block_view().
 */
function utexas_social_accounts_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'social_accounts_block':
      $block['content'] = social_accounts_block_view();
      break;
  }

  return $block;
}

/**
 * Implements social_accounts_block_view().
 *
 * Custom function that defines how the new block will be displayed.
 */
function social_accounts_block_view() {
  $block = array();
  // Build the block content.
  $content = '<ul class="connect-links">';

  $accounts = unserialize(variable_get('utexas_social_accounts_media_items', UTEXAS_SOCIAL_ACCOUNTS_MEDIA_ITEMS));
  $sorted_fields = array();
  $count = 0;
  foreach (array_keys($accounts) as $name) {
    $machine_name = _utexas_admin_machine_name($name);
    // Get social account weight or default to -10.
    $weight = variable_get('utexas_social_accounts_' . $machine_name . '_weight', $count);
    $sorted_fields[$name] = $weight;
    $count++;
  }
  // Sort by value (weight).
  asort($sorted_fields);
  foreach ($sorted_fields as $name => $weight) {
    $machine_name = _utexas_admin_machine_name($name);
    $url = variable_get('utexas_social_accounts_' . $machine_name, '');
    if ($url != '') {
      $content .= '<li><a href="' . $url . '" class="connect-link"><span class="' . $accounts[$name] . '"><span class="hiddenText">' . $name . '</span></span></a></li>';
    }
  }
  $content .= '</ul>';

  // Block output in HTML with div wrapper.
  $block = array(
    'content' => array(
      '#prefix' => '',
      '#type' => 'markup',
      '#markup' => $content,
      '#suffix' => '',
    ),
  );

  return $block;
}
