<?php

/**
 * @file
 * Install for CPE initial deployment.
 */

 /**
 * Implements hook_install().
 */
function cpe_deployment_install() {
  drupal_set_installed_schema_version('cpe_deployment', 7100);
}

/**
 * Implements hook_update_N().
 *
 * Generate initial taxonomy terms.
 */
function cpe_deployment_update_7101() {
  // Enable the following Features/Modules.
  $enable = array(
    '',
  );

  module_enable($enable);

  // Install CPE Taxonomy terms.
  _install_taxonomy_terms();
}
