<?php

/**
 * @file
 * CPE Deployment module.
 */

 /**
  * Helper function to add default taxonomy terms.
  */
function _install_taxonomy_terms() {
  // Create Course Type Vocabulary.
  $course_types_vocab = (object) array(
    'name' => 'Course Types',
    'description' => 'The type of course being created.',
    'machine_name' => 'cpe_course_type_vocab',
  );

  taxonomy_vocabulary_save($course_types_vocab);

  $course_types = array(
    'Course',
    'Webinar',
    'Information Session',
    'Specialist Program',
  );

  // Create the taxonomy terms.
  foreach ($course_types as $weight => $type) {
    _create_taxonomy_term($type, $course_types_vocab->vid, $weight);
  }

  // Create Section Type Vocabulary.
  $section_types_vocab = (object) array(
    'name' => 'Section Types',
    'description' => 'The type of section being created.',
    'machine_name' => 'cpe_section_type_vocab',
  );

  taxonomy_vocabulary_save($section_types_vocab);

  $section_types = array(
    'Course',
    'Single Course Certificate',
  );

  // Create the taxonomy terms.
  foreach ($section_types as $weight => $type) {
    _create_taxonomy_term($type, $section_types_vocab->vid, $weight);
  }

  // Create Modality Vocabulary.
  $modality_vocab = (object) array(
    'name' => 'Modality',
    'description' => 'The different ways a course is offered.',
    'machine_name' => 'cpe_modality_vocab',
  );

  taxonomy_vocabulary_save($modality_vocab);

  $modality = array(
    'Online',
    'In-person',
    'Online Self-paced',
    'Online Cohort-based',
  );

  // Create the taxonomy terms.
  foreach ($modality as $weight => $type) {
    _create_taxonomy_term($type, $modality_vocab->vid, $weight);
  }

}

/**
 * Helper function to create a taxonomy term.
 */
function _create_taxonomy_term($name, $vid, $weight = NULL, $parent_tid = NULL) {
  $term = new stdClass();
  $term->name = $name;
  $term->vid = $vid;
  if ($weight) {
    $term->weight = $weight;
  }
  if ($parent_tid) {
    $term->parent = array($parent_tid);
  }
  taxonomy_term_save($term);
  return $term;
}
