<?php
/**
 * @file
 * Custom field definition for the Resource Field form element.
 */

/**
 * Implements hook_field_info().
 *
 * Defines the Resource Field field.
 */
function utexas_resource_field_info() {
  return array(
    'utexas_resource' => array(
      'label' => t('Resource'),
      'description' => t('This field stores information about resources'),
      'settings' => array(),
      'instance_settings' => array(),
      'default_widget' => 'utexas_resource',
      'default_formatter' => 'utexas_resource',
    ),
  );
}

/**
 * Implements hook_image_default_styles().
 *
 * Defines image styles for resource images.
 */
function utexas_resource_image_default_styles() {
  return array(
    'utexas_resource_image' => array(
      'label' => t('Resource Image'),
      'effects' => array(
        array(
          'name' => 'smartcrop_scale_and_crop',
          'data' => array(
            'width' => 400,
            'height' => 250,
            'upscale' => FALSE,
          ),
          'weight' => 0,
        ),
      ),
    ),
  );
}

/**
 * Implements hook_field_widget_info().
 *
 * Defines two widgets for the Resources Field.
 */
function utexas_resource_field_widget_info() {
  return array(
    'utexas_resource' => array(
      'label' => t('Resource'),
      'field types' => array('utexas_resource'),
      'settings' => array(
        'max_links' => 5,
      ),
    ),
  );
}

/**
 * Implements hook_field_widget_settings_form().
 *
 * Has one option to determine the maximum number of links available.
 */
function utexas_resource_field_widget_settings_form($field, $instance) {
  $widget = $instance['widget'];
  $settings = $widget['settings'];
  $form = array();

  switch ($widget['type']) {
    case 'utexas_resource':
      $form['max_links'] = array(
        '#type' => 'textfield',
        '#title' => t('Max number of links'),
        '#description' => t('Enter a maximum number of links that the field can support. Recommended to be no greater than 8.'),
        '#default_value' => $settings['max_links'],
        '#required' => TRUE,
        '#element_validate' => array('element_validate_integer_positive'),
      );

      break;
  }

  return $form;
}

/**
 * Implements hook_field_widget_form().
 *
 * Defines two widget forms for the Resources Field.
 */
function utexas_resource_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  switch ($instance['widget']['type']) {

    case 'utexas_resource':
      if ($delta == 0) {
        // Title. Make this only available on the first item.
        $element['title'] = array(
          '#type' => 'textfield',
          '#title' => t('Title'),
          '#description' => t('Optionally add a title for the collection of resources.'),
          '#size' => 60,
          '#maxlength' => 100,
          '#default_value' => (isset($items[$delta]['title'])) ? $items[$delta]['title'] : '',
        );
      }

      // Image upload.
      $element['image'] = array(
        '#type' => 'media',
        '#title' => t('Resource Image'),
        '#tree' => TRUE,
        '#field_name' => 'file_upload',
        '#description' => t('Upload an image, or select one from the library. Image will be automatically cropped to 400 x 250.'),
        '#extended' => TRUE,
        '#media_options' => array(
          'global' => array(
            'file_extensions' => 'gif png jpg jpeg',
            'file_directory' => 'resource-images',
            'types' => array('image'),
          ),
        ),
        '#default_value' => array('fid' => isset($items[$delta]['image_fid']) ? $items[$delta]['image_fid'] : 0),
      );

      // Headline.
      $element['headline'] = array(
        '#type' => 'textfield',
        '#title' => t('Headline'),
        '#description' => t('Enter a headline for this resource.'),
        '#size' => 60,
        '#maxlength' => 100,
        '#default_value' => (isset($items[$delta]['headline'])) ? $items[$delta]['headline'] : '',
      );

      // Links.
      $element['links'] = array(
        '#type' => 'fieldset',
        '#collapsible' => FALSE,
        '#title' => t('Links'),
      );

      // Build the elements for the Links.
      $links = array();
      $link_delta = 0;
      $stored_links = (isset($items[$delta]['links']) && is_string($items[$delta]['links'])) ? unserialize($items[$delta]['links']) : FALSE;
      if ($stored_links != FALSE) {
        for ($link_delta = 0; $link_delta < count($stored_links); $link_delta++) {
          if (isset($stored_links[$link_delta])) {
            // Populate existing links.
            $links[] = array(
              'link_title' => array(
                '#type' => 'textfield',
                '#maxlength' => 128,
                '#default_value' => $stored_links[$link_delta]['link_title'],
              ),
              'link_url' => array(
                '#type' => 'textfield',
                '#maxlength' => 255,
                '#default_value' => drupal_get_path_alias($stored_links[$link_delta]['link_url']),
              ),
              '_weight' => array(
                '#type' => 'weight',
                '#default_value' => $stored_links[$link_delta]['_weight'],
                '#delta' => 10,
                '#title_display' => 'invisible',
                '#title' => t('Weight for Link'),
              ),
            );
          }
        }
      }
      // Fill up remaining slots with empty rows till the default limit.
      while ($link_delta < $instance['widget']['settings']['max_links'] - 1) {
        $links[] = _utexas_resource_add_link_empty_row($link_delta);
        $link_delta++;
      }

      // Ensure there is always one empty row available.
      $links[] = _utexas_resource_add_link_empty_row($link_delta);

      // Attach the remainder of the form.
      $element['links'] = $links;
      $element['links']['#theme'] = 'utexas_resource_link_table';
      $element['links'] += array(
        '#type' => 'fieldset',
        '#title' => t('Links'),
        '#description' => t('The link title is limited to 128 characters maximum.  If items are full, an additional row will be provided upon save.'),
      );

      break;

  }

  return $element;
}

/**
 * Implements hook_field_validate().
 *
 * Used to make sure all fields have valid data in them.
 */
function utexas_resource_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  // Loop through the values, making sure all check out.
  foreach ($items as $delta => $item) {
    if (!utexas_resource_field_is_empty($item, $field)) {
      // Check to make sure headline is not empty.
      if (empty($item['headline'])) {
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error' => 'headline_empty',
          'message' => t('%headline: Headline field is required.', array('%headline' => $instance['label'])),
        );
      }
      // Bypass if coming from a migration.
      $image = isset($item['image']['fid']) ? $item['image']['fid'] : 0;

      if (isset($item['links'])) {
        // Make sure links are valid links.
        if (is_array($item['links'])) {
          foreach ($item['links'] as $key => $link) {
            $target = drupal_get_normal_path($link['link_url']);
            if (!empty($link['link_url']) and !drupal_valid_path($target)) {
              $errors[$field['field_name']][$langcode][$delta][] = array(
                'error' => 'link_invalid',
                'message' => t('%field: The path provided is not a valid URL alias or external link.',
                array('%field' => $instance['label'])),
              );
            }
            if (!empty($link['link_title']) and empty($link['link_url'])) {
              $errors[$field['field_name']][$langcode][$delta][] = array(
                'error' => 'title_no_link',
                'message' => t('%field: There is a title but no corresponding link.',
                array('%field' => $instance['label'])),
              );
            }
            if (empty($link['link_title']) and !empty($link['link_url'])) {
              $errors[$field['field_name']][$langcode][$delta][] = array(
                'error' => 'link_no_title',
                'message' => t('%field: There is a link but no corresponding title.',
                array('%field' => $instance['label'])
                ),
              );
            }
          }
        }
      }
    }
  }
}

/**
 * Implements hook_field_widget_error().
 *
 * Applies sub-field errors to individual form elements.
 */
function utexas_resource_field_widget_error($element, $error, $form, &$form_state) {
  // Set sub-field errors.
  switch ($error['error']) {
    case 'headline_empty':
      form_error($element['headline'], $error['message']);
      break;

    case 'title_no_link':
      // Loop through the links, flagging all of the elements with a problem.
      foreach (element_children($element['links']) as $key) {
        $link = $element['links'][$key];
        if (!empty($link['link_title']['#value']) and empty($link['link_url']['#value'])) {
          form_error($element['links'][$key]['link_url'], $error['message']);
        }
      }
      break;

    case 'link_invalid':
      // Loop through the links, flagging all of the elements with a problem.
      foreach (element_children($element['links']) as $key) {
        $link = $element['links'][$key];
        $target = drupal_get_normal_path($link['link_url']['#value']);
        if (!empty($link['link_url']['#value']) and !drupal_valid_path($target)) {
          form_error($element['links'][$key]['link_url'], $error['message']);
        }
      }
      break;

    case 'link_no_title':
      // Loop through the links, flagging all of the elements with a problem.
      foreach (element_children($element['links']) as $key) {
        $link = $element['links'][$key];
        if (!empty($link['link_url']['#value']) and empty($link['link_title']['#value'])) {
          form_error($element['links'][$key]['link_title'], $error['message']);
        }
      }
      break;
  }
}

/**
 * Implements hook_field_presave().
 *
 * Adjust copy format+value and handle images.
 */
function utexas_resource_field_presave($entity_type, $entity, $field, $instance, $langcode, &$items) {
  // Throw the copy format & copy value into separate files.
  foreach ($items as $delta => &$item) {
    // Determine whether the image is coming from a form or directly from the
    // database, as in the case of a migration.
    if (isset($item['image']['fid'])) {
      $item['image_fid'] = $item['image']['fid'];
    }
    // A migration with no image sends null; file_save needs 0.
    if (empty($item['image_fid'])) {
      $item['image_fid'] = 0;
    }

    if (empty($item['links'])) {
      $item['links'] = array();
    }
    // Adjust links to strip out random empty strings.
    $item['links'] = _utexas_resource_order_links($item['links']);
    $tmp_links = array();
    $tmp_delta = -10;

    foreach ($item['links'] as $key => &$link) {
      if (!empty($link['link_title']) and !empty($link['link_url'])) {
        // Store Drupal path aliases as internal paths, if they exist.
        $target = drupal_get_normal_path($link['link_url']);
        $tmp_links[] = array(
          'link_title' => $link['link_title'],
          'link_url' => $target,
          '_weight' => $tmp_delta,
        );

        $tmp_delta++;
      }
    }
    $item['links'] = serialize($tmp_links);
  }
}

/**
 * Implements hook_file_download().
 *
 * Checks access to make sure users can actually use the files that have been
 * uploaded. Required since Drupal 7.29.
 */
function utexas_resource_file_download($uri) {
  if (strpos(file_uri_target($uri), 'resource_images') === 0) {
    $info = image_get_info($uri);
    return array('Content-Type' => $info['mime_type']);
  }
  return NULL;
}

/**
 * Implements hook_field_insert().
 *
 * Increment file usage.
 */
function utexas_resource_field_insert($entity_type, $entity, $field, $instance, $langcode, &$items) {
  utexas_admin_field_insert_custom($entity_type, $entity, $field, $instance, $langcode, $items, 'utexas_resource');
}


/**
 * Implements hook_field_update().
 *
 * Adjust copy format+value and handle images.
 */
function utexas_resource_field_update($entity_type, $entity, $field, $instance, $langcode, &$items) {
  utexas_admin_field_update_custom($entity_type, $entity, $field, $instance, $langcode, $items, 'utexas_resource');
}

/**
 * Implements hook_field_delete().
 *
 * Cleans up any remaining files, if they have not been deleted already.
 */
function utexas_resource_field_delete($entity_type, $entity, $field, $instance, $langcode, &$items) {
  utexas_admin_field_delete_custom($entity_type, $entity, $field, $instance, $langcode, $items, 'utexas_resource');
}

/**
 * Implements hook_field_is_empty().
 */
function utexas_resource_field_is_empty($item, $field) {
  switch ($field['type']) {
    case 'utexas_resource':
      // An empty image from a Migration will send "MigrateFileFid".
      $image_empty = (isset($item['image'])) ? empty($item['image']['fid']) : empty($item['image_fid']);
      if (isset($item['image_fid'])) {
        if ($item['image_fid'] == 'MigrateFileFid') {
          $image_empty = TRUE;
        }
      }
      // An empty headline from a migration will send NULL.
      if (isset($item['headline'])) {
        if ($item['headline'] == '') {
          unset($item['headline']);
        }
      }
      // An empty title from a migration will send NULL.
      if (isset($item['title'])) {
        if ($item['title'] == '') {
          unset($item['title']);
        }
      }

      return empty($item['headline']) and
        empty($item['link']) and
        $image_empty;
  }

  return FALSE;
}

/**
 * Helper function that returns an array representing an empty row.
 *
 * @param int $link_count
 *   Number of links on the form.
 *
 * @return array
 *   Render array for the links.
 */
function _utexas_resource_add_link_empty_row($link_count) {
  // Define the next one down.
  $max_delta = 10;

  return array(
    'link_title' => array(
      '#type' => 'textfield',
      '#maxlength' => 128,
    ),
    'link_url' => array(
      '#type' => 'textfield',
      '#maxlength' => 255,
      '#attributes' => array(
        'placeholder' => 'external URL (http://...) or internal path (e.g., about/diversity)',
      ),
    ),
    '_weight' => array(
      '#type' => 'weight',
      '#delta' => $max_delta,
      '#default_value' => ($max_delta - $link_count) * -1,
      '#title_display' => 'invisible',
      '#title' => t('Weight for Link'),
    ),
  );
}

/**
 * Custom theme function to theme the link table as a tabledrag element.
 */
function theme_utexas_resource_link_table($variables) {
  $element = $variables['element'];
  $output = '';

  $table_id = drupal_html_id($element['#id'] . '_values');
  $order_class = $element['#id'] . '-delta-order';

  $header = array(
    array('data' => t('Link Title'), 'colspan' => 2),
    t('Link URL'),
    t('Weight'),
  );
  $rows = array();

  // Sort links according to weight.
  $items = array();
  foreach (element_children($element) as $key) {
    $items[] = &$element[$key];
  }
  usort($items, '_utexas_resource_sort_links_by_weight');

  // Add the links as table rows.
  foreach ($items as $key => $item) {
    $item['_weight']['#attributes']['class'] = array($order_class);
    $delta_element = drupal_render($item['_weight']);
    $cells = array(
      array('data' => '', 'class' => array('field-multiple-drag')),
      drupal_render($item['link_title']),
      drupal_render($item['link_url']),
      array('data' => $delta_element, 'class' => array('delta-order')),
    );
    $rows[] = array(
      'data' => $cells,
      'class' => array('draggable'),
      'id' => $table_id . '-' . $key,
    );
  }

  // Create the table drag.
  $output  = '<div class="link-table">';
  $output .= theme('table', array(
    'header' => $header,
    'rows' => $rows,
    'attributes' => array(
      'id' => $table_id,
    ),
  ));
  $output .= '</div>';

  // Order the table drag.
  drupal_add_tabledrag($table_id, 'order', 'sibling', $order_class);

  return $output;
}

/**
 * Helper function to order links by weight.
 */
function _utexas_resource_sort_links_by_weight($a, $b) {
  if (isset($a['_weight']) and isset($b['_weight'])) {
    return ($a['_weight']['#value'] < $b['_weight']['#value']) ? -1 : 1;
  }
  return 0;
}

/**
 * Implements hook_field_formatter_info().
 *
 * Defines two formatters for the Resources Field.
 */
function utexas_resource_field_formatter_info() {
  return array(
    'utexas_resource' => array(
      'label' => t('Resource Unit'),
      'field types' => array('utexas_resource'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 *
 * Builds the two formatter views for the Resources Field.
 */
function utexas_resource_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $settings = $display['settings'];

  switch ($display['type']) {
    case 'utexas_resource':
      foreach ($items as $delta => $item) {
        $element[] = array(
          '#type' => 'markup',
          '#markup' => theme('utexas_resource', $item),
          '#attached' => array(
            'css' => array(drupal_get_path('module', 'utexas_resource') . '/utexas_resource.css'),
          ),
        );
      }

      break;

  }

  return $element;
}

/**
 * Implements hook_theme().
 *
 * Register the resource displays.
 */
function utexas_resource_theme($existing, $type, $theme, $path) {
  return array(
    'utexas_resource' => array(
      'variables' => array(
        'title' => NULL,
        'delta' => NULL,
        'headline' => NULL,
        'image_fid' => NULL,
        'links' => NULL,
      ),
      'template' => 'theme/utexas-resource',
    ),
    'utexas_resource_link_table' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Theme preprocess function for resources.
 *
 * @see utexas-resource.tpl.php
 */
function template_preprocess_utexas_resource(&$variables) {
  // Attach some theme hook suggestions to override individual resources.
  $variables['theme_hook_suggestions'] = array(
    'utexas-resource',
    'utexas-resource--' . $variables['id'],
  );

  // Adjust passed in variables.
  $image_fid = $variables['image_fid'];
  $headline = check_plain($variables['headline']);
  $links = !empty($variables['links']) ? unserialize($variables['links']) : array();

  $image = FALSE;
  // Get an image loaded.
  if (!empty($variables['image_fid'])) {
    if ($file = file_load($variables['image_fid'])) {
      $info = image_get_info($file->uri);
      $alt = isset($file->field_file_image_alt_text['und'][0]['safe_value']) ? $alt = $file->field_file_image_alt_text['und'][0]['safe_value'] : '';
      $title = isset($file->field_file_image_title_text['und'][0]['safe_value']) ? $title = $file->field_file_image_title_text['und'][0]['safe_value'] : '';
      $image = theme('image_style', array(
        'style_name' => 'utexas_resource_image',
        'path' => $file->uri,
        'width' => $info['width'],
        'height' => $info['height'],
        'alt' => $alt,
        'title' => $title,
        'attributes' => array('class' => array('resource-image')),
      ));
    }
  }

  // Set the image variable to pass to the template.
  $variables['image'] = (isset($image)) ? $image : FALSE;

  // Get a link-ified headline, if necessary.
  $variables['headline_text'] = $variables['headline'];
  if (!empty($variables['link'])) {
    $variables['headline'] = l($variables['headline'], $variables['link'], array(
      'attributes' => array(
        'class' => array('headline-link'),
      ),
    ));
  }

  // Set the links.
  $tmp_links = array();
  foreach ($links as $link) {
    $tmp_links[] = l('<span>' . $link['link_title'] . '</span>', $link['link_url'], array(
      'attributes' => array(
        'class' => array(
          'cta-link',
          'sans',
          'flex-content-cta',
        ),
      ),
      'html' => TRUE,
    ));
  }

  // If no image is present add block-grid class to list of links.
  $variables['no_image'] = '';
  if ($image == FALSE) {
    $variables['no_image'] = 'small-block-grid-2';
  }

  $variables['links'] = (!count($tmp_links)) ? FALSE : theme('item_list', array(
    'items' => $tmp_links,
    'title' => '',
    'type' => 'ul',
    'attributes' => array(
      'class' => array('resource_links', $variables['no_image']),
    ),
  ));

}

/**
 * Helper function to determine whether or not an array of links is empty.
 *
 * @param string $links
 *   A serialized array representing link form information.
 *
 * @return bool
 *   A boolean representing whether or not that row of links is empty or not.
 */
function _utexas_resource_links_are_empty($links) {
  $empty = TRUE;

  // Ensure a sanitation of weights + other items.
  $links = _utexas_resource_order_links($links);

  // We only care if link title or link URL is set.
  if (!empty($links)) {
    // An empty array can be sent via migration.
    $links = (is_array($links)) ? $links : unserialize($links);
    foreach ($links as $link) {
      if (!empty($link['link_title']) or !empty($link['link_url'])) {
        $empty = FALSE;
      }
    }
  }
  return $empty;
}

/**
 * Helper function to sort ordered links by their weight.
 *
 * @param string $item
 *   Serialiezd array for an individual link row.
 *
 * @return array
 *   A sorted array of links.
 */
function _utexas_resource_order_links($item) {

  // Loop through, unsetting the delete link & setting by weights.
  $weight = array();
  $title = array();
  // Determine whether the data is coming from the form or the database,
  // as in the case of a migration.
  $item = (is_array($item)) ? $item : unserialize($item);
  if (!empty($item)) {
    foreach ($item as $key => &$link) {
      $weight[$key] = (int) $link['_weight'];
      $title[$key] = $link['link_title'];
    }

    // Sort by weight, then title and return.
    array_multisort($weight, SORT_ASC, $title, SORT_ASC, $item);

    // Strip out empty fields.
    foreach ($item as $key => &$link) {
      if (empty($link['link_title']) and empty($link['link_url'])) {
        unset($link);
      }
    }
  }
  return $item;
}
