<?php

/**
 * @file
 * CPE Admin module.
 *
 * Used to add custom logic to CPE site.
 */

// Give the date format type a machine name.
define('CPE_ADMIN_DATE_TYPE', 'cpe_admin_date_type');

// Define the string to be passed to date().
define('CPE_ADMIN_DATE_FORMAT', 'g:i a');

/**
 * Implements hook_date_formats().
 */
function cpe_admin_date_formats() {
  $formats = array();
  $formats[] = array(
    'type' => CPE_ADMIN_DATE_TYPE,
    'format' => CPE_ADMIN_DATE_FORMAT,
    'locales' => array(),
  );

  variable_set('date_format_' . CPE_ADMIN_DATE_TYPE, CPE_ADMIN_DATE_FORMAT);

  return $formats;
}

/**
 * Implements hook_date_format_types().
 */
function cpe_admin_date_format_types() {
  $types = array();
  $types[CPE_ADMIN_DATE_TYPE] = t('Times');
  return $types;
}
